name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches:
      - main  # Oder dein primärer Branch-Name

permissions:
  contents: write # Erlaubt das Schreiben auf den gh-pages Branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html # Der Ordner, den Doxygen erstellt hat
          branch: gh-pages # Ziel-Branch für die Website